apiVersion: skaffold/v2alpha1
kind: Config
metadata:
  name: your-organization
build:
  local: {}
  tagPolicy:
    sha256: {}
  artifacts:
  - image: your-organization/accounts-service
    context: .
    docker:
      dockerfile: accounts-service.Dockerfile
  - image: your-organization/edge-service
    context: .
    docker:
      dockerfile: edge-service.Dockerfile
deploy:
  helm:
    releases:
    - name: your-organization-edge-service
      chartPath: deploy/charts/edge-service
      values:
        image: your-organization/edge-service
      useHelmSecrets: true
      valuesFiles:
      - deploy/charts/edge-service/values.yaml
    - name: your-organization-accounts-service
      chartPath: deploy/charts/accounts-service
      values:
        image: your-organization/accounts-service
      useHelmSecrets: true
      valuesFiles:
      - deploy/charts/accounts-service/values.yaml
