apiVersion: skaffold/v2alpha1
kind: Config
metadata:
  name: samo
build:
  local: {}
  tagPolicy:
    sha256: {}
  artifacts:
  - image: samo/edge-service
    context: .
    docker:
      dockerfile: edge-service.Dockerfile
  - image: samo/accounts-service
    context: .
    docker:
      dockerfile: accounts-service.Dockerfile
  - image: samo/accounts-view
    context: .
    docker:
      dockerfile: accounts-view.Dockerfile
deploy:
  helm:
    releases:
    - name: samo-kafka-setup
      chartPath: deploy/charts/kafka-setup
    - name: samo-edge-service
      chartPath: deploy/charts/edge
      values:
        image: samo/edge-service
      useHelmSecrets: true
      valuesFiles:
      - deploy/charts/values.yaml
    - name: samo-accounts-service
      chartPath: deploy/charts/accounts
      values:
        image: samo/accounts-service
      useHelmSecrets: true
      valuesFiles:
      - deploy/charts/values.yaml
    - name: samo-accounts-view
      chartPath: deploy/charts/accounts
      values:
        image: samo/accounts-view
      useHelmSecrets: true
      valuesFiles:
      - deploy/charts/values.yaml
